[package]
name = "term-color"
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"

[dependencies]
thiserror = "1.0.56"

[target.'cfg(unix)'.dependencies]
libc = "0.2.151"
mio = { version = "0.8.10", features = ["os-poll", "os-ext"], default-features = false }

[workspace]
members = [
    "termtheme"
]
