[package]
name = "terminal-colorsaurus"
description = "Provides a handle to the terminal of the current process"
readme = "readme.md"
repository = "https://github.com/bash/terminal-colorsaurus"
categories = ["command-line-interface"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
rust-version = "1.70.0"
exclude = [".github", ".gitignore", "*.sh"]

[dependencies]
thiserror = "1.0.56"
rgb = { version = "0.8.37", optional = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2.151"
mio = { version = "0.8.10", features = ["os-poll", "os-ext"], default-features = false }
terminal-trx = { git = "https://github.com/bash/terminal-trx" }

[target.'cfg(windows)'.dependencies]
terminal-trx = { git = "https://github.com/bash/terminal-trx" }
windows-sys = { version = "0.52.0", features = ["Win32_System_Threading", "Win32_System_Console", "Win32_Foundation"] }

[features]
__docs = []
__nightly = []
__test_readme = []

[package.metadata.docs.rs]
features = ["__docs", "__nightly"]
