[package]
name = "terminal-colorsaurus"
description = "Determines the background and foreground color of the terminal"
readme = "readme.md"
repository = "https://github.com/bash/terminal-colorsaurus"
categories = ["command-line-interface"]
license = "MIT OR Apache-2.0"
version = "0.3.3"
edition = "2021"
rust-version = "1.70.0"
exclude = [".github", ".gitignore", "*.sh", "benchmark/**/*"]

[dependencies]
thiserror = "1.0.56"
rgb = { version = "0.8.37", optional = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2.151"
memchr = "2.7.1"
mio = { version = "0.8.11", features = ["os-poll", "os-ext"], default-features = false }
terminal-trx = "0.2.0"

[lints.rust]
missing_debug_implementations = "warn"
missing_docs = "warn"

[lints.clippy]
unimplemented = "warn"
undocumented_unsafe_blocks = "deny"
dbg_macro = "warn"
exhaustive_enums = "warn"
exhaustive_structs = "warn"
unwrap_used = "deny"
use_debug = "warn"

[package.metadata.docs.rs]
features = ["rgb"]
rustdoc-args = ["--cfg", "docsrs"]

[workspace]
members = ["examples/*"]
