[graph]
all-features = true

[output]
feature-depth = 1

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
]
confidence-threshold = 1.0

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
    { crate = "windows-sys", reason = "an old version is used by mio, see https://github.com/tokio-rs/mio/pull/1820 for updating it" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
