name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        min-rust-version: [true, false]
    steps:
    - uses: actions/checkout@v3
    - name: Use Minimum Rust Version
      if: matrix.min-rust-version
      run: ./use-min-rust-version.sh
    - name: Build
      run: cargo build --all-features
    - name: Check format
      run: cargo fmt -- --check
    - name: Docs
      run: cargo doc --all-features
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --all-features
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- --deny warnings
