name: CI

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --all-features
    - name: Check format
      run: cargo fmt -- --check

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --all-features
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- --deny warnings
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install nightly
    - name: Build Docs
      run: cargo +nightly doc --all-features
      env:
        RUSTDOCFLAGS: -Dwarnings --cfg docsrs
